language: node_js
node_js: "10.11.0"
if: tag IS present
cache: yarn
install:
  - yarn
script: 
  - yarn test:unit
  - yarn build
  # - yarn build:doc
after_success:
  - codecov

deploy:
  - provider: npm
    email: zhurui0904@gmail.com
    api_key: $AUTH_TOKEN
    on:
      tags: true
      branch: master
    skip_cleanup: true
  # - provider: pages
  #   skip_cleanup: true
  #   github_token: $GITHUB_TOKEN
  #   keep_history: true
  #   target_branch: master
  #   on:
  #     branch: master
